# Generated by Django 4.2.30 on 2026-08-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Override auto-generated canonical if required', null=True)),
                ('og_title', models.CharField(blank=True, max_length=70, null=True)),
                ('og_description', models.CharField(blank=True, max_length=160, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo_og/')),
                ('no_index', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('description_blocks', models.JSONField(blank=True, default=list, help_text='Structured block data for future rich text editors')),
                ('project_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_industries', models.ManyToManyField(blank=True, related_name='projects', to='industries.industry')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_projects', to='products.media')),
                ('products_used', models.ManyToManyField(blank=True, related_name='projects', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.media')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
