# Generated by Django 4.2.30 on 2026-08-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-project_date', '-created_at']},
        ),
    ]
