# Generated by Django 4.2.30 on 2026-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
