# Generated by Django 4.2.30 on 2026-08-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Override auto-generated canonical if required', null=True)),
                ('og_title', models.CharField(blank=True, max_length=70, null=True)),
                ('og_description', models.CharField(blank=True, max_length=160, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo_og/')),
                ('no_index', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('description_blocks', models.JSONField(blank=True, default=list, help_text='Structured block data for future rich text editors')),
                ('applications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industries', to='products.media')),
                ('related_products', models.ManyToManyField(blank=True, related_name='industries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
    ]
