# Generated by Django 4.2.30 on 2026-08-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Industries'},
        ),
    ]
