# Generated by Django 5.2.16 on 2026-08-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'sort_order']},
        ),
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='FAQ items: [{"question": "...", "answer": "..."}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Key features/benefits list — one per line'),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, help_text='Surface finish (e.g. Hot-Dip Galvanized, Painted)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Primary material (e.g. Steel, FRP, Aluminium)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO reference (not rendered in HTML)', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Internal product code or SKU', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Select up to 4 related products shown at the bottom of the detail page', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='standard',
            field=models.CharField(blank=True, help_text='Applicable standards (e.g. EN ISO 1461, BS 4592)', max_length=200),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='short_description',
            field=models.TextField(blank=True, help_text='Shown on category cards and the products listing page'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text="Descriptive alt text for SEO — e.g. 'Hot-dip galvanized steel grating installed in UAE industrial facility'", max_length=200),
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark as the primary/hero image shown first in gallery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='applications',
            field=models.TextField(blank=True, help_text='Applications text — can be comma-separated or prose'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Full product overview — shown in the Product Overview section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Structured block data for block editors (e.g. EditorJS)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(help_text='Shown on product cards and hero summary (2–3 sentences)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Technical spec key-value map (legacy / quick entry)'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Specification label (e.g. 'Bearing Bar Size')", max_length=100)),
                ('value', models.CharField(help_text="Specification value (e.g. '25×3 mm')", max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_rows', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'ordering': ['sort_order'],
            },
        ),
    ]
